name: Test
description: test Masfix compiler with test.py

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install nasm and mingw (Chocolatey)
        shell: cmd
        run: |
          nasm -v || choco install -y nasm
          gcc -v || choco install -y mingw

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Test with test.py
        shell: cmd
        run: python test.py run
